services:
  smp:
    build:
      context: ./smp-server/
      args:
        RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./data/smp/universe:/server/universe
      - ./data/smp/databases:/server/databases
      - ./data/smp/logs:/server/logs
    ports:
      - "25565:25565"
      - "25575:25575"

  smp-backup:
    depends_on:
      smp:
        condition: service_healthy
    image: itzg/mc-backup
    environment:
      BACKUP_NAME: "smp"
      BACKUP_METHOD: "tar"
      SRC_DIR: "/data/"
      INCLUDES: "./smp/universe/,./smp/databases/EasyAuth/"
      BACKUP_INTERVAL: "8h"
      BACKUP_ON_STARTUP: "false"
      PRUNE_BACKUP_DAYS: "7"
      RCON_HOST: "smp"
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    volumes:
      - ./data/smp/universe:/data/smp/universe:ro
      - ./data/smp/databases:/data/smp/databases:ro
      - ./data/smp-backup/backups:/backups

  rcon:
    depends_on:
      smp:
        condition: service_healthy
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - rcon:/opt/rcon-web-admin/db
    environment:
      RWA_USERNAME: "admin"
      RWA_PASSWORD: "${RCON_WEB_ADMIN_PASSWORD}"
      RWA_ADMIN: "true"

      RWA_RCON_HOST: "smp"
      RWA_RCON_PORT: "25575"
      RWA_RCON_PASSWORD: "${RCON_PASSWORD}"
      RWA_GAME: "minecraft"
      RWA_SERVER_NAME: "Cake SMP"

volumes:
  rcon:
