services:
  smp:
    build:
      context: ./smp-server/
      args:
        RCON_PASSWORD: ${RCON_PASSWORD}
    healthcheck:
      test: [ "CMD", "mc-monitor", "status", "--host", "localhost", "--port", "25565" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 60s
    volumes:
      - ./data/smp/server:/server:z,U
    ports:
      - "25565:25565"
      - "25575:25575"

  smp-backup:
    depends_on:
      smp:
        condition: service_healthy
    image: docker.io/itzg/mc-backup
    environment:
      BACKUP_NAME: "smp"
      BACKUP_METHOD: "tar"
      SRC_DIR: "/data/"
      INCLUDES: "./smp/universe/,./smp/databases/EasyAuth/"
      BACKUP_INTERVAL: "8h"
      BACKUP_ON_STARTUP: "false"
      PRUNE_BACKUP_DAYS: "7"
      RCON_HOST: "smp"
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    volumes:
      - ./data/smp/server:/data/smp:ro,z
      - ./data/smp-backup/backups:/backups:z,U

  rcon:
    depends_on:
      smp:
        condition: service_healthy
    image: docker.io/itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - rcon:/opt/rcon-web-admin/db
    environment:
      RWA_USERNAME: "admin"
      RWA_PASSWORD: "${RCON_WEB_ADMIN_PASSWORD}"
      RWA_ADMIN: "true"

      RWA_RCON_HOST: "smp"
      RWA_RCON_PORT: "25575"
      RWA_RCON_PASSWORD: "${RCON_PASSWORD}"
      RWA_GAME: "minecraft"
      RWA_SERVER_NAME: "Cake SMP"

  www:
    image: docker.io/library/caddy:2
    # note for podman: to allow binding to ports < 1024, you need to run the following command:
    # echo 80 | sudo tee /proc/sys/net/ipv4/ip_unprivileged_port_start
    # this will change the minimum port number for unprivileged users to bind to
    # it will be reset to 1024 on reboot
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./web-server/caddy/:/etc/caddy/:ro
      - ./web-server/www/:/www/:ro
      - ./data/smp/server/squaremap/web:/webmap:ro,z
      - caddy_data:/data
      - caddy_config:/config
    environment:
      BASE_DOMAIN: "cake-smp.local"

volumes:
  rcon:
  caddy_data:
  caddy_config:
