name = "Cake SMP"
mc_version = "1.21.7"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "aikars"
game_args = "--universe ./universe/"
memory = "4G"

[markdown]
files = ["README.md"]
auto_update = true

[options]

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "JIZogEYa"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "mccDBWqV"

[[mods]]
type = "modrinth"
id = "easyauth"
version = "MsfOax3L"

[[mods]]
type = "modrinth"
id = "easywhitelist"
version = "9OoxSFQz"

[[mods]]
type = "modrinth"
id = "ledger"
version = "f3h7no4G"

[[mods]]
type = "modrinth"
id = "universal-graves"
version = "gdZmLCZD"

[[mods]]
type = "modrinth"
id = "chunky"
version = "inWDi2cf"

[[mods]]
type = "modrinth"
id = "sleep-warp-updated"
version = "2AMKOBLR"

[[mods]]
type = "modrinth"
id = "sit!"
version = "ImC46K5m"

[[mods]]
type = "modrinth"
id = "otterlib"
version = "LTg9ifOT"

[[mods]]
type = "modrinth"
id = "squaremap"
version = "Gvw4v06M"

# [[mods]]
# type = "modrinth"
# id = "disable-end"
# version = "PpFBmw8r"

[[mods]]
type = "modrinth"
id = "simple-server-links"
version = "LdRUojjV"
