name = "Cake SMP"
mc_version = "1.21.5"

[jar]
type = "fabric"
loader = "latest"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "aikars"
game_args = "--universe ./universe/"
memory = "6G"

[markdown]
files = ["README.md"]
auto_update = true

[options]

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "FZ4q3wQK"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "E4WyjCxJ"

[[mods]]
type = "modrinth"
id = "easyauth"
version = "MdRRckj6"

[[mods]]
type = "modrinth"
id = "easywhitelist"
version = "4ndHE533"

[[mods]]
type = "modrinth"
id = "ledger"
version = "cyKd32dm"

[[mods]]
type = "modrinth"
id = "universal-graves"
version = "ejJjBZIM"

[[mods]]
type = "modrinth"
id = "chunky"
version = "mhLtMoLk"

[[mods]]
type = "modrinth"
id = "sleep-warp-updated"
version = "vnRGqK0o"

[[mods]]
type = "modrinth"
id = "sit!"
version = "QTTlGVkz"

[[mods]]
type = "modrinth"
id = "squaremap"
version = "L1i3PIWB"

[[mods]]
type = "modrinth"
id = "disable-end"
version = "PpFBmw8r"
